modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/allaryin/Incubation/issues"
license="LGPL-2.1"
[[mods]]
modId="incubation"
version="1.1.0"
displayName="Incubation"
displayURL="https://www.curseforge.com/minecraft/mc-mods/incubation"
logoFile="logo.png"
credits="Markus1002, Translators: vhslance, F4zzer, peehpeh, xM4RCOSx, XanaSago, Rye"
authors="Markus1002, allaryin"
description='''Adds chicken nests and makes eggs more useful.'''
[[dependencies.incubation]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incubation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"